version: '3.8'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=development_pass
      - POSTGRES_DB="books-api"
    volumes:
      - books-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
#  api:
#    build:
#      context: .
#      dockerfile: docker/Dockerfile.debug
#    container_name: api
#    command: node_modules/.bin/ts-node-dev --poll --exit-child --debug --respawn --inspect=0.0.0.0:9229 src/app.ts
#    ports:
#      - 3000:3000
#      - 9229:9229
#    volumes:
#      - ./src:/app/src

volumes:
  books-db-data:
    driver: local